apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ratify.fullname" . }}-configuration
data:
  config.json: |
    {
      "executor": {
        "verificationRequestTimeout": {{ .Values.provider.timeout.validationTimeoutSeconds | int | mul 1000 | add -100 }},
        "mutationRequestTimeout": {{ .Values.provider.timeout.mutationTimeoutSeconds | int | mul 1000 | add -50 }}
      },
      "store": {
        "version": "1.0.0",
        "useHttp": {{ .Values.oras.useHttp }},
        "plugins": [
            {
                "name": "oras"
            }
        ]
      },
      "policy": {
        "version": "1.0.0",
        "plugin": {
            "name": "configPolicy"
        }
      },
      "verifier": {
          "version": "1.0.0",
          "plugins": [
            {
                "name":"notaryv2",
                "artifactTypes" : "application/vnd.cncf.notary.signature",
                "verificationCertStores": {
                  "certs":[
                   ]
                },
                "trustPolicyDoc": {
                  "version": "1.0",
                  "trustPolicies": [
                    {
                      "name": "default",
                      "registryScopes": [ "none/none" ],
                      "signatureVerification": {
                        "level" : "strict" 
                      },
                      "trustStores": ["ca:certs"],
                      "trustedIdentities": ["*"]
                    }
                  ]
                }
            }
          ]
      }
    }
