{{- if or .Values.azureWorkloadIdentity.clientId .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "ratify.labels" . | nindent 4 }}
    azure.workload.identity/use: "true"
  name: {{ include "ratify.serviceAccountName" . }}
{{- end }}